### ISSUE TITLE
Animation Unpacker/Repacker tool

### ISSUE THREAD

**Issue by dir3kous** [rumblerosesxx/RRXX-Mod-Howto#1]
Hello.
I am interested in creating a converter for RumbleRose motion. (In the past I have written parsers to convert FIFA ea3 to fbx, etc.)

I was gathering information about the "Animation Unpacker/Repacker tool" mentioned in Animations.md, but I could not get any good information. (Is it a tool created by `EatRawMeat391` ?)

If you have it, could you upload it to the repository like other tools?

**Comment by rumblerosesxx** [comment]
I think it might be a paid tool by the svr people I'm not too sure. Drop by the discord, there are a couple other people working on animations that should be able to help discord.gg/GmTNjEVPra
